name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # once daily at midnight UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: mgi25
          outputs: |
            ./github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake.svg
      - name: push github-contribution-grid-snake.svg to the output branch
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Generate contribution snake"
          add: "./github-contribution-grid-snake.svg ./output/github-contribution-grid-snake.svg"
